### ISSUE TITLE
About Git LFS

### ISSUE THREAD

**Issue by avery-k** [MicrobialDarkMatter/ccvae#1]
I'm trying to get files in data/strong100/，like segment_ground_truth.tsv. so I'm using git-lfs, but it doesn't seem to be working, can you provide a new address to help me solve this problem? I would be very grateful if you could help me!

> /code/ccvae/data/strong100$ git-lfs clone https://github.com/MicrobialDarkMatter/ccvae.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
正克隆到 'ccvae'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 99 (delta 20), reused 96 (delta 17), pack-reused 0
展开对象中: 100% (99/99), 155.33 KiB | 384.00 KiB/s, 完成.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/MicrobialDarkMatter/ccvae.git/info/lfs'

> git log --all -p -S e23ea59ef1e9f567e18f6b5f7f5e2d1775af654616b68441b80e3bf889fd8c7c
commit c9031d22f9a7e520b26b27b400295dd4f4c1a434
Author: Andre Lamurias <andrel@cs.aau.dk>
Date:   Fri Jan 27 11:50:00 2023 +0100

    add data files

diff --git a/data/strong100/amber_gs.tsv b/data/strong100/amber_gs.tsv
new file mode 100644
index 0000000..32e5683
--- /dev/null
+++ b/data/strong100/amber_gs.tsv
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:e23ea59ef1e9f567e18f6b5f7f5e2d1775af654616b68441b80e3bf889fd8c7c
+size 21119

commit b4f3c4871f22f9e6844c2f1c2a9a3afa18454dbe
Author: Andre Lamurias <andrel@cs.aau.dk>
Date:   Wed Jan 25 15:52:31 2023 +0100

    add data

diff --git a/data/strong100/amber_gs.tsv b/data/strong100/amber_gs.tsv
new file mode 100644
index 0000000..32e5683
--- /dev/null
+++ b/data/strong100/amber_gs.tsv
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:e23ea59ef1e9f567e18f6b5f7f5e2d1775af654616b68441b80e3bf889fd8c7c
+size 21119

commit 8ebfbe62b8abdc0a478459ab845484d8fe4267a7
Author: Andre Lamurias <andrel@cs.aau.dk>
Date:   Wed Jan 25 15:49:43 2023 +0100

    Revert "add data"

    This reverts commit 35d05f75d5c956df0b8157d4e0ca82d53d762b25.

diff --git a/data/data/strong100/amber_gs.tsv b/data/data/strong100/amber_gs.tsv
deleted file mode 100644
index 32e5683..0000000
--- a/data/data/strong100/amber_gs.tsv
+++ /dev/null
@@ -1,3 +0,0 @@
-version https://git-lfs.github.com/spec/v1
-oid sha256:e23ea59ef1e9f567e18f6b5f7f5e2d1775af654616b68441b80e3bf889fd8c7c
-size 21119

commit 997a516ed7e71a05903c54b790ed8745c6cacb9f
Author: Andre Lamurias <andrel@cs.aau.dk>
Date:   Wed Jan 25 15:41:23 2023 +0100

    add data

diff --git a/data/data/strong100/amber_gs.tsv b/data/data/strong100/amber_gs.tsv
new file mode 100644
index 0000000..32e5683
--- /dev/null
+++ b/data/data/strong100/amber_gs.tsv
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:e23ea59ef1e9f567e18f6b5f7f5e2d1775af654616b68441b80e3bf889fd8c7c
+size 21119

**Comment by AndreLamurias** [comment]
Hi avery-k,
the strong100 dataset is available here: https://drive.google.com/file/d/1eqT8zO94W1I1eyD0fosP8W2WCm84q_nD/view?usp=sharing
